# Generated by Django 6.0.6 on 2026-06-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default="'item_images/food1.jpeg", upload_to='item_images/'),
        ),
    ]
