# Generated by Django 6.0.6 on 2026-06-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='item_images/food1.jpeg', upload_to='item_images/'),
        ),
    ]
